# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'login.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(559, 451)
        Dialog.setMinimumSize(QtCore.QSize(559, 451))
        Dialog.setMaximumSize(QtCore.QSize(559, 451))
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("images/校徽.jpeg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        Dialog.setWindowIcon(icon)
        self.lineEdit_username = QtWidgets.QLineEdit(Dialog)
        self.lineEdit_username.setGeometry(QtCore.QRect(260, 240, 113, 21))
        self.lineEdit_username.setObjectName("lineEdit_username")
        self.lineEdit_password = QtWidgets.QLineEdit(Dialog)
        self.lineEdit_password.setGeometry(QtCore.QRect(260, 300, 113, 21))
        self.lineEdit_password.setEchoMode(QtWidgets.QLineEdit.Password)
        self.lineEdit_password.setObjectName("lineEdit_password")
        self.passwordLabel = QtWidgets.QLabel(Dialog)
        self.passwordLabel.setGeometry(QtCore.QRect(160, 300, 51, 21))
        self.passwordLabel.setStyleSheet("font: 10pt \"宋体\";")
        self.passwordLabel.setObjectName("passwordLabel")
        self.usernameLable = QtWidgets.QLabel(Dialog)
        self.usernameLable.setGeometry(QtCore.QRect(160, 240, 72, 15))
        self.usernameLable.setStyleSheet("font: 10pt \"宋体\";")
        self.usernameLable.setObjectName("usernameLable")
        self.btn_ok = QtWidgets.QPushButton(Dialog)
        self.btn_ok.setGeometry(QtCore.QRect(210, 360, 111, 31))
        self.btn_ok.setStyleSheet("font: 10pt \"宋体\";")
        self.btn_ok.setObjectName("btn_ok")
        self.label_state = QtWidgets.QLabel(Dialog)
        self.label_state.setGeometry(QtCore.QRect(10, 270, 72, 15))
        self.label_state.setText("")
        self.label_state.setObjectName("label_state")
        self.label = QtWidgets.QLabel(Dialog)
        self.label.setGeometry(QtCore.QRect(70, 150, 411, 51))
        self.label.setStyleSheet("font: 14pt \"仿宋\";")
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(Dialog)
        self.label_2.setGeometry(QtCore.QRect(220, 10, 120, 120))
        self.label_2.setText("")
        self.label_2.setPixmap(QtGui.QPixmap("images/crane.jpeg"))
        self.label_2.setScaledContents(True)
        self.label_2.setObjectName("label_2")

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "登录"))
        self.passwordLabel.setText(_translate("Dialog", "密 码"))
        self.usernameLable.setText(_translate("Dialog", "用户名"))
        self.btn_ok.setText(_translate("Dialog", "登录"))
        self.label.setText(_translate("Dialog", "大型港口起重机智能健康监测系统登录"))
